watch.dir=C:/Users/Jesús Rodríguez/Documents/CASSINI/Dataset 1 1
ipfs.api.base=http://127.0.0.1:5001
fabric.bridge.base=http://192.168.136.130:8088
fabric.source=windows-ipfs-uploader
fabric.enabled=true

state.file=C:/Users/Jesús Rodríguez/Documents/CASSINI/ipfs-folder-uploader/state/processed-state.jsonl

retry.max.attempts=5
retry.initial.delay.ms=3000

file.stability.wait.ms=700
file.stability.checks=10